baseurl = "http://dingboche4410.com"
title = "Dingboche 4410m"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = false
disableKinds=["RSS"]

[params]
  description = '<!--[-->Dingboche is a small Sherpa village in the Khumbu Valley of Nepal, at 4410m.<br/>It all started here, on a brief afternoon ... followed by New Zealand, Switzerland<br/> and being continued in many other places...<!--]-->'
  logo = "fa-diamond"
  copyright = ""

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = '<!--[-->german translation to be done<!--]-->'

[languages.pt]
languageName = "Português"
weight = 3
title = "Dimension"
description = '<!--[-->to be done<!--]-->'
